# Generated by Django 3.0.7 on 2020-06-06 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urlcut', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urlpair',
            name='full_url',
            field=models.URLField(),
        ),
    ]
