# Generated by Django 3.0.7 on 2020-06-06 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urlcut', '0002_auto_20200606_0530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urlpair',
            name='short_url',
            field=models.CharField(db_index=True, default='', max_length=50, unique=True),
        ),
    ]
